// Copyright 2024 The Flutter Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:cross_file/cross_file.dart';
import 'package:dartantic_interface/dartantic_interface.dart';
import 'package:flutter/foundation.dart';

/// An abstract class representing a chat history provider.
///
/// This class defines the interface for interacting with different LLM
/// services while maintaining chat history. Implementations of this class
/// should provide the logic for generating text responses based on input
/// prompts and managing conversation history.
abstract class ChatHistoryProvider implements Listenable {
  /// Transcribes audio to text using the LLM.
  ///
  /// [audioFile] is the audio file to transcribe.
  ///
  /// Returns a [Stream] of [String] containing the transcribed text chunks.
  /// This allows for streaming responses as they are generated by the LLM.
  Stream<String> transcribeAudio(XFile audioFile);

  /// Generates a stream of text based on the given prompt and attachments.
  /// Interacts with a chat and builds on the history of the chat associated
  /// with the provider.
  ///
  /// This method should be implemented to interact with the specific LLM
  /// service and generate text responses.
  ///
  /// [prompt] is the input text to generate a response for.
  /// [attachments] is an optional iterable of [Part] objects to include with
  /// the prompt. These can be data parts (images, files) or link parts that
  /// provide additional context for the LLM.
  ///
  /// Returns a [Stream] of [String] containing the generated text chunks. This
  /// allows for streaming responses as they are generated by the LLM.
  Stream<String> sendMessageStream(String prompt, {Iterable<Part> attachments});

  /// Returns an iterable of [ChatMessage] objects representing the chat
  /// history.
  ///
  /// This getter provides access to the conversation history maintained by the
  /// provider. The history typically includes both user messages and model
  /// responses in chronological order.
  ///
  /// Returns an [Iterable] of [ChatMessage] objects.
  Iterable<ChatMessage> get history;

  /// Sets the chat history to the provided messages.
  ///
  /// This setter allows updating the conversation history maintained by the
  /// provider. The provided [history] replaces the existing history with a new
  /// set of messages.
  ///
  /// [history] is an [Iterable] of [ChatMessage] objects representing the new
  /// chat history.
  set history(Iterable<ChatMessage> history);
}

/// A function that generates a stream of text based on a prompt and
/// attachments.
typedef ChatStreamGenerator =
    Stream<String> Function(
      String prompt, {
      required Iterable<Part> attachments,
    });
